### PR TITLE
mg - added margin to 'New Office Hour' button in OfficeHours.js

### PR DESCRIPTION
**Pull request by moisesgtz**

### CODE REVIEW

**Review by namabilly — DISMISSED** [review]
LGTM, except the extra blank space before the closing >. It's only a matter of style, doesn't matter to functionality.

**Review by btk5h — DISMISSED** [review]
Can you revert your changes to `secrets-localhost.properties.SAMPLE` and `application.properties`?

**Review by carsoncoley — APPROVED** [review]
LGTM

**Review by namabilly — APPROVED** [review]
LGTM

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
