### PR TITLE
Updated footer message 6pm-3

### PR DESCRIPTION
**Pull request by CalvinJenkins**
Updated footer message to say "This app is a class project of CMPSC 156 at UCSB. Check out the source code on GitHub!" with hyperlinks for "CMPSC 156", "UCSB", and "Github". Added tests for each hyperlink.

### CODE REVIEW

**Review by Bryanz2019 — COMMENTED** [review]
The changes made in AppFooter.js passed the test and everything, but the example shown in the instruction has a hyperlink for the keywords "on Github", not sure what's going on.

Screen Shot 2021-02-23 at 8 00 56 PM

**Comment by mara-downing** [comment]
> The changes made in AppFooter.js passed the test and everything, but the example shown in the instruction has a hyperlink for the keywords "on Github", not sure what's going on.
> 
> Screen Shot 2021-02-23 at 8 00 56 PM

What browser are you using? I just redeployed on qa to check and it looks fine there.

**Comment by andrewhlu** [comment]
Can you add those who worked on this PR to the "Assignees" list, the "w21-6pm-3" label into the "Labels" list, and link this PR's corresponding issue under "Linked Issues" or by editing your PR description to have a closing keyword followed by the issue number?

**Comment by pconrad** [comment]
Please take a look at this checklist for PRs: https://ucsb-cs156.github.io/topics/pull_requests/

**Review by Carinaqyy — APPROVED** [review]
The changes look good to me.

**Review by Bryanz2019 — APPROVED** [review]
LGTM

**Review by jvogit — APPROVED** [review]
disregard

**Review by jvoucsb — APPROVED** [review]
LGTM

**Pull request merged**
