### PR TITLE
pb: changed title of web page to 'UCSB CS LAs', completing issue #93

### PR DESCRIPTION
**Pull request by ohsnapitssunny**
Changed the app title from "Demo CRA + Spring App" to "UCSB CS LAs"

### CODE REVIEW

**Review by peterbayerle — DISMISSED** [review]

**Comment by pconrad** [comment]
There is a merge conflict in `javascript/package-lock.json`.

The best way to resolve that is this:
* cd into `javascript`
* delete `package-lock.json`
* run `npm install`
* commit the new `package-lock.json`

With luck, this eliminates the merge conflict.
If not, then ask the staff for help.

**Comment by pconrad** [comment]
Currently showing:

image


Please see: 

https://ucsb-cs156.github.io/topics/spring_react_package_lock_json_merge_conflicts/

**Comment by pconrad** [comment]
Also, when you are ready for this to be reviewed, change it from a draft PR to a regular PR by clicking the "Ready for Review" button:

image

**Review by pconrad — CHANGES_REQUESTED** [review]
My review was requested, but this PR is still a "draft PR".  

In any case, I suggest updating the package-lock.json (per my comments) and changing from draft PR to regular PR.  Then it's probably good to go.

**Review by peterbayerle — APPROVED** [review]

**Review by pranav01acharya — APPROVED** [review]

**Review by jvoucsb — DISMISSED** [review]
The change is looks good. 

However, I don't believe this PR should update the `package-lock.json`. This should be a separate issue outside the scope of #93. My suggestion is to remove the changes to the `package-lock.json`. Let me know if you suggest otherwise.

**Comment by jvoucsb** [comment]
> > The change is looks good.
> > However, I don't believe this PR should update the `package-lock.json`. This should be a separate issue outside the scope of #93. My suggestion is to remove the changes to the `package-lock.json`. Let me know if you suggest otherwise.
> 
> I made the updates to `package-lock.json` to resolve the merge conflict Prof Conrad mentions earlier in this issue. Did I address this merge conflict the wrong way?

`npm install` may have generated a `package-lock.json` with updated versions for some dependencies which I think caused the merge conflict issue in the first place. I think in this case the updates seem fine and the app deployed with no issue and functionality seems fine. So I think the change might be fine.

It just seems to me that modifying the `package-lock.json` for this particular issue is unnecessary. It might be nit picky but I think in general changing unrelated files that are not necessary for the issue may have unintended side effects.

**Review by pranav01acharya — APPROVED** [review]

**Review by jvoucsb — APPROVED** [review]
LGTM. Appreciate the changes!

**Pull request merged**
